name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Install dependencies
      run: make unit_tests

    - name: Run check
      run: make all
