name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Install dependencies
      run: make

    - name: Run mkfs
      run: make mkfs
    - name: Run fsck
      run: make fsck
    - name: Run tune
      run: make tune
    - name: Run unpack
      run: make unpack
